#ifndef __PROTOCOL_H__
#define __PROTOCOL_H__

// Generated by tools/idl_gen/gen.py from main.idl, do not edit

#include "ezxml.h"
#include <message.h>
#include <director.h>
#include <connectr.h>
#include <connecti.h>
#include <authenti.h>
#include <authen1.h>
#include <statusre.h>
#include <status.h>
#include <direct1.h>
#include <direc2.h>
#include <fileread.h>
#include <filedata.h>
#include <filewrit.h>
#include <filewr1.h>

// Protocol message handler types
typedef void(*ConnectRequest_Handler)(const ConnectRequest*);
typedef void(*ConnectionRequestReply_Handler)(const ConnectionRequestReply*);
typedef void(*Authenticate_Handler)(const Authenticate*);
typedef void(*AuthenticationStatus_Handler)(const AuthenticationStatus*);
typedef void(*StatusRequest_Handler)(const StatusRequest*);
typedef void(*Status_Handler)(const Status*);
typedef void(*DirectoryListRequest_Handler)(const DirectoryListRequest*);
typedef void(*DirectoryList_Handler)(const DirectoryList*);
typedef void(*FileReadRequest_Handler)(const FileReadRequest*);
typedef void(*FileData_Handler)(const FileData*);
typedef void(*FileWriteRequest_Handler)(const FileWriteRequest*);
typedef void(*FileWriteReply_Handler)(const FileWriteReply*);

class Protocol {
public:

    Protocol() : m_ConnectRequest_handler(NULL), m_ConnectionRequestReply_handler(NULL), m_Authenticate_handler(NULL), m_AuthenticationStatus_handler(NULL), m_StatusRequest_handler(NULL), m_Status_handler(NULL), m_DirectoryListRequest_handler(NULL), m_DirectoryList_handler(NULL), m_FileReadRequest_handler(NULL), m_FileData_handler(NULL), m_FileWriteRequest_handler(NULL), m_FileWriteReply_handler(NULL)
    {}

    virtual ~Protocol() {}

    // message creators, the caller owns the returned object
    ConnectRequest* create_ConnectRequest(const std::string& p_platform, const std::string& p_unique_id);
    ConnectionRequestReply* create_ConnectionRequestReply(bool p_accepted, bool p_authentication_required, const std::string& p_host_name);
    Authenticate* create_Authenticate(const std::string& p_user_name_hash, const std::string& p_password_hash);
    AuthenticationStatus* create_AuthenticationStatus(bool p_success, const std::string& p_rights);
    StatusRequest* create_StatusRequest();
    Status* create_Status(const std::string& p_host_platform, const std::vector<std::string>& p_drives, const std::vector<long>& p_free_space, const std::vector<std::string>& p_working_directories, int p_current__work_index);
    DirectoryListRequest* create_DirectoryListRequest(const std::string& p_directory_hash, int p_start);
    DirectoryList* create_DirectoryList(const std::string& p_directory_name, const std::string& p_directory_hash, int p_start, int p_total, const std::string& p_error, const std::vector<DirectoryEntry>& p_entries);
    FileReadRequest* create_FileReadRequest(const std::string& p_file_hash, long p_offset, int p_length);
    FileData* create_FileData(const std::string& p_file_hash, long p_offset, const std::string& p_data, bool p_eof, const std::string& p_error);
    FileWriteRequest* create_FileWriteRequest(const std::string& p_directory_hash, const std::string& p_name, long p_offset, const std::string& p_data, bool p_last);
    FileWriteReply* create_FileWriteReply(const std::string& p_name, long p_offset, bool p_ok, const std::string& p_error);

    // message handler setters
    void set_ConnectRequest_Handler(ConnectRequest_Handler p_handler) {
        m_ConnectRequest_handler = p_handler;
    }
    void set_ConnectionRequestReply_Handler(ConnectionRequestReply_Handler p_handler) {
        m_ConnectionRequestReply_handler = p_handler;
    }
    void set_Authenticate_Handler(Authenticate_Handler p_handler) {
        m_Authenticate_handler = p_handler;
    }
    void set_AuthenticationStatus_Handler(AuthenticationStatus_Handler p_handler) {
        m_AuthenticationStatus_handler = p_handler;
    }
    void set_StatusRequest_Handler(StatusRequest_Handler p_handler) {
        m_StatusRequest_handler = p_handler;
    }
    void set_Status_Handler(Status_Handler p_handler) {
        m_Status_handler = p_handler;
    }
    void set_DirectoryListRequest_Handler(DirectoryListRequest_Handler p_handler) {
        m_DirectoryListRequest_handler = p_handler;
    }
    void set_DirectoryList_Handler(DirectoryList_Handler p_handler) {
        m_DirectoryList_handler = p_handler;
    }
    void set_FileReadRequest_Handler(FileReadRequest_Handler p_handler) {
        m_FileReadRequest_handler = p_handler;
    }
    void set_FileData_Handler(FileData_Handler p_handler) {
        m_FileData_handler = p_handler;
    }
    void set_FileWriteRequest_Handler(FileWriteRequest_Handler p_handler) {
        m_FileWriteRequest_handler = p_handler;
    }
    void set_FileWriteReply_Handler(FileWriteReply_Handler p_handler) {
        m_FileWriteReply_handler = p_handler;
    }

    /**
     * Deserializes the given <o> node as the message type and calls its handler.
     * Returns 1 if the message was handled, 0 otherwise.
     **/
    int receive(const char* p_message_type, ezxml_t p_o);

private:

    ConnectRequest_Handler m_ConnectRequest_handler;
    ConnectionRequestReply_Handler m_ConnectionRequestReply_handler;
    Authenticate_Handler m_Authenticate_handler;
    AuthenticationStatus_Handler m_AuthenticationStatus_handler;
    StatusRequest_Handler m_StatusRequest_handler;
    Status_Handler m_Status_handler;
    DirectoryListRequest_Handler m_DirectoryListRequest_handler;
    DirectoryList_Handler m_DirectoryList_handler;
    FileReadRequest_Handler m_FileReadRequest_handler;
    FileData_Handler m_FileData_handler;
    FileWriteRequest_Handler m_FileWriteRequest_handler;
    FileWriteReply_Handler m_FileWriteReply_handler;

};
#endif
