// Generated by tools/idl_gen/gen.py from main.idl, do not edit

#include "protocol.h"
#include <log.h>
#include <string.h>

int Protocol::receive(const char* p_message_type, ezxml_t p_o)
{
    if(!strcmp(p_message_type, "ConnectRequest"))
    {
        if(!m_ConnectRequest_handler) { log_warning() << "No handler for ConnectRequest"; return 0; }
        ConnectRequest obj;
        if(!obj.deserialize(p_o)) { log_error() << "Cannot deserialize ConnectRequest"; return 0; }
        m_ConnectRequest_handler(&obj);
        return 1;
    }
    if(!strcmp(p_message_type, "ConnectionRequestReply"))
    {
        if(!m_ConnectionRequestReply_handler) { log_warning() << "No handler for ConnectionRequestReply"; return 0; }
        ConnectionRequestReply obj;
        if(!obj.deserialize(p_o)) { log_error() << "Cannot deserialize ConnectionRequestReply"; return 0; }
        m_ConnectionRequestReply_handler(&obj);
        return 1;
    }
    if(!strcmp(p_message_type, "Authenticate"))
    {
        if(!m_Authenticate_handler) { log_warning() << "No handler for Authenticate"; return 0; }
        Authenticate obj;
        if(!obj.deserialize(p_o)) { log_error() << "Cannot deserialize Authenticate"; return 0; }
        m_Authenticate_handler(&obj);
        return 1;
    }
    if(!strcmp(p_message_type, "AuthenticationStatus"))
    {
        if(!m_AuthenticationStatus_handler) { log_warning() << "No handler for AuthenticationStatus"; return 0; }
        AuthenticationStatus obj;
        if(!obj.deserialize(p_o)) { log_error() << "Cannot deserialize AuthenticationStatus"; return 0; }
        m_AuthenticationStatus_handler(&obj);
        return 1;
    }
    if(!strcmp(p_message_type, "StatusRequest"))
    {
        if(!m_StatusRequest_handler) { log_warning() << "No handler for StatusRequest"; return 0; }
        StatusRequest obj;
        if(!obj.deserialize(p_o)) { log_error() << "Cannot deserialize StatusRequest"; return 0; }
        m_StatusRequest_handler(&obj);
        return 1;
    }
    if(!strcmp(p_message_type, "Status"))
    {
        if(!m_Status_handler) { log_warning() << "No handler for Status"; return 0; }
        Status obj;
        if(!obj.deserialize(p_o)) { log_error() << "Cannot deserialize Status"; return 0; }
        m_Status_handler(&obj);
        return 1;
    }
    if(!strcmp(p_message_type, "DirectoryListRequest"))
    {
        if(!m_DirectoryListRequest_handler) { log_warning() << "No handler for DirectoryListRequest"; return 0; }
        DirectoryListRequest obj;
        if(!obj.deserialize(p_o)) { log_error() << "Cannot deserialize DirectoryListRequest"; return 0; }
        m_DirectoryListRequest_handler(&obj);
        return 1;
    }
    if(!strcmp(p_message_type, "DirectoryList"))
    {
        if(!m_DirectoryList_handler) { log_warning() << "No handler for DirectoryList"; return 0; }
        DirectoryList obj;
        if(!obj.deserialize(p_o)) { log_error() << "Cannot deserialize DirectoryList"; return 0; }
        m_DirectoryList_handler(&obj);
        return 1;
    }
    if(!strcmp(p_message_type, "FileReadRequest"))
    {
        if(!m_FileReadRequest_handler) { log_warning() << "No handler for FileReadRequest"; return 0; }
        FileReadRequest obj;
        if(!obj.deserialize(p_o)) { log_error() << "Cannot deserialize FileReadRequest"; return 0; }
        m_FileReadRequest_handler(&obj);
        return 1;
    }
    if(!strcmp(p_message_type, "FileData"))
    {
        if(!m_FileData_handler) { log_warning() << "No handler for FileData"; return 0; }
        FileData obj;
        if(!obj.deserialize(p_o)) { log_error() << "Cannot deserialize FileData"; return 0; }
        m_FileData_handler(&obj);
        return 1;
    }
    if(!strcmp(p_message_type, "FileWriteRequest"))
    {
        if(!m_FileWriteRequest_handler) { log_warning() << "No handler for FileWriteRequest"; return 0; }
        FileWriteRequest obj;
        if(!obj.deserialize(p_o)) { log_error() << "Cannot deserialize FileWriteRequest"; return 0; }
        m_FileWriteRequest_handler(&obj);
        return 1;
    }
    if(!strcmp(p_message_type, "FileWriteReply"))
    {
        if(!m_FileWriteReply_handler) { log_warning() << "No handler for FileWriteReply"; return 0; }
        FileWriteReply obj;
        if(!obj.deserialize(p_o)) { log_error() << "Cannot deserialize FileWriteReply"; return 0; }
        m_FileWriteReply_handler(&obj);
        return 1;
    }
    log_warning() << "Unknown message:" << p_message_type;
    return 0;
}

ConnectRequest* Protocol::create_ConnectRequest(const std::string& p_platform, const std::string& p_unique_id)
{
    return new ConnectRequest(p_platform, p_unique_id);
}

ConnectionRequestReply* Protocol::create_ConnectionRequestReply(bool p_accepted, bool p_authentication_required, const std::string& p_host_name)
{
    return new ConnectionRequestReply(p_accepted, p_authentication_required, p_host_name);
}

Authenticate* Protocol::create_Authenticate(const std::string& p_user_name_hash, const std::string& p_password_hash)
{
    return new Authenticate(p_user_name_hash, p_password_hash);
}

AuthenticationStatus* Protocol::create_AuthenticationStatus(bool p_success, const std::string& p_rights)
{
    return new AuthenticationStatus(p_success, p_rights);
}

StatusRequest* Protocol::create_StatusRequest()
{
    return new StatusRequest();
}

Status* Protocol::create_Status(const std::string& p_host_platform, const std::vector<std::string>& p_drives, const std::vector<long>& p_free_space, const std::vector<std::string>& p_working_directories, int p_current__work_index)
{
    return new Status(p_host_platform, p_drives, p_free_space, p_working_directories, p_current__work_index);
}

DirectoryListRequest* Protocol::create_DirectoryListRequest(const std::string& p_directory_hash, int p_start)
{
    return new DirectoryListRequest(p_directory_hash, p_start);
}

DirectoryList* Protocol::create_DirectoryList(const std::string& p_directory_name, const std::string& p_directory_hash, int p_start, int p_total, const std::string& p_error, const std::vector<DirectoryEntry>& p_entries)
{
    return new DirectoryList(p_directory_name, p_directory_hash, p_start, p_total, p_error, p_entries);
}

FileReadRequest* Protocol::create_FileReadRequest(const std::string& p_file_hash, long p_offset, int p_length)
{
    return new FileReadRequest(p_file_hash, p_offset, p_length);
}

FileData* Protocol::create_FileData(const std::string& p_file_hash, long p_offset, const std::string& p_data, bool p_eof, const std::string& p_error)
{
    return new FileData(p_file_hash, p_offset, p_data, p_eof, p_error);
}

FileWriteRequest* Protocol::create_FileWriteRequest(const std::string& p_directory_hash, const std::string& p_name, long p_offset, const std::string& p_data, bool p_last)
{
    return new FileWriteRequest(p_directory_hash, p_name, p_offset, p_data, p_last);
}

FileWriteReply* Protocol::create_FileWriteReply(const std::string& p_name, long p_offset, bool p_ok, const std::string& p_error)
{
    return new FileWriteReply(p_name, p_offset, p_ok, p_error);
}

