# Generated by tools/idl_gen/gen.py from main.idl, do not edit
"""The cloudy message protocol, Python side."""

import itertools
import xml.etree.ElementTree as ET
from xml.sax.saxutils import escape

_ENVELOPE_HEAD = '<?xml version="1.0" encoding="UTF-8" standalone="yes" ?><protocol><cld v="1.0" msg="'

_sequence = itertools.count(1)


class _Object:
    NAME = ""
    # (attribute name, kind, item class name or kind for lists)
    FIELDS = ()

    def serialize(self):
        out = ["<o><type>", self.NAME, "</type><attributes>"]
        for name, kind, item in self.FIELDS:
            value = getattr(self, name)
            out.append("<" + name + ">")
            if kind == "list":
                for v in value:
                    out.append("<item>" + _to_text(item, v) + "</item>")
            else:
                out.append(_to_text(kind, value))
            out.append("</" + name + ">")
        out.append("</attributes></o>")
        return "".join(out)

    @classmethod
    def from_node(cls, o):
        if o is None or o.findtext("type") != cls.NAME:
            return None
        attrs = o.find("attributes")
        if attrs is None:
            return None
        obj = cls()
        for name, kind, item in cls.FIELDS:
            node = attrs.find(name)
            if node is None:
                continue
            if kind == "list":
                setattr(obj, name, [_from_item(item, i) for i in node.findall("item")])
            else:
                setattr(obj, name, _from_text(kind, node.text))
        return obj

    def __repr__(self):
        return self.NAME + "(" + ", ".join(n + "=" + repr(getattr(self, n)) for n, _, _ in self.FIELDS) + ")"


def _to_text(kind, value):
    if kind in _CLASSES:
        return value.serialize()
    if kind == "string":
        return escape(value or "")
    if kind == "bool":
        return "1" if value else "0"
    return str(value)


def _from_text(kind, text):
    text = text or ""
    if kind == "string":
        return text
    if kind == "bool":
        return text.strip() in ("1", "true")
    if kind == "float":
        return float(text or 0)
    return int(text or 0)


def _from_item(kind, node):
    if kind in _CLASSES:
        return _CLASSES[kind].from_node(node.find("o"))
    return _from_text(kind, node.text)


class Message(_Object):
    NAME = "Message"
    FIELDS = _Object.FIELDS + (("message_id", "int", "int"), )

    def __init__(self):
        self.message_id = next(_sequence)


class DirectoryEntry(_Object):
    NAME = "DirectoryEntry"
    FIELDS = _Object.FIELDS + (("name", "string", "string"), ("date", "int", "int"), ("time", "int", "int"), ("size", "int", "int"), ("attrs", "string", "string"), ("hash", "string", "string"), )

    def __init__(self, name="", date=0, time=0, size=0, attrs="", hash=""):
        self.name = name
        self.date = date
        self.time = time
        self.size = size
        self.attrs = attrs
        self.hash = hash


class ConnectRequest(Message):
    NAME = "ConnectRequest"
    FIELDS = Message.FIELDS + (("platform", "string", "string"), ("unique_id", "string", "string"), )

    def __init__(self, platform="", unique_id=""):
        self.platform = platform
        self.unique_id = unique_id
        self.message_id = next(_sequence)


class ConnectionRequestReply(Message):
    NAME = "ConnectionRequestReply"
    FIELDS = Message.FIELDS + (("accepted", "bool", "bool"), ("authentication_required", "bool", "bool"), ("host_name", "string", "string"), )

    def __init__(self, accepted=False, authentication_required=False, host_name=""):
        self.accepted = accepted
        self.authentication_required = authentication_required
        self.host_name = host_name
        self.message_id = next(_sequence)


class Authenticate(Message):
    NAME = "Authenticate"
    FIELDS = Message.FIELDS + (("user_name_hash", "string", "string"), ("password_hash", "string", "string"), )

    def __init__(self, user_name_hash="", password_hash=""):
        self.user_name_hash = user_name_hash
        self.password_hash = password_hash
        self.message_id = next(_sequence)


class AuthenticationStatus(Message):
    NAME = "AuthenticationStatus"
    FIELDS = Message.FIELDS + (("success", "bool", "bool"), ("rights", "string", "string"), )

    def __init__(self, success=False, rights=""):
        self.success = success
        self.rights = rights
        self.message_id = next(_sequence)


class StatusRequest(Message):
    NAME = "StatusRequest"
    FIELDS = Message.FIELDS + ()

    def __init__(self):
        self.message_id = next(_sequence)


class Status(Message):
    NAME = "Status"
    FIELDS = Message.FIELDS + (("host_platform", "string", "string"), ("drives", "list", "string"), ("free_space", "list", "int"), ("working_directories", "list", "string"), ("current__work_index", "int", "int"), )

    def __init__(self, host_platform="", drives=None, free_space=None, working_directories=None, current__work_index=0):
        self.host_platform = host_platform
        self.drives = drives if drives is not None else []
        self.free_space = free_space if free_space is not None else []
        self.working_directories = working_directories if working_directories is not None else []
        self.current__work_index = current__work_index
        self.message_id = next(_sequence)


class DirectoryListRequest(Message):
    NAME = "DirectoryListRequest"
    FIELDS = Message.FIELDS + (("directory_hash", "string", "string"), ("start", "int", "int"), )

    def __init__(self, directory_hash="", start=0):
        self.directory_hash = directory_hash
        self.start = start
        self.message_id = next(_sequence)


class DirectoryList(Message):
    NAME = "DirectoryList"
    FIELDS = Message.FIELDS + (("directory_name", "string", "string"), ("directory_hash", "string", "string"), ("start", "int", "int"), ("total", "int", "int"), ("error", "string", "string"), ("entries", "list", "DirectoryEntry"), )

    def __init__(self, directory_name="", directory_hash="", start=0, total=0, error="", entries=None):
        self.directory_name = directory_name
        self.directory_hash = directory_hash
        self.start = start
        self.total = total
        self.error = error
        self.entries = entries if entries is not None else []
        self.message_id = next(_sequence)


class FileReadRequest(Message):
    NAME = "FileReadRequest"
    FIELDS = Message.FIELDS + (("file_hash", "string", "string"), ("offset", "int", "int"), ("length", "int", "int"), )

    def __init__(self, file_hash="", offset=0, length=0):
        self.file_hash = file_hash
        self.offset = offset
        self.length = length
        self.message_id = next(_sequence)


class FileData(Message):
    NAME = "FileData"
    FIELDS = Message.FIELDS + (("file_hash", "string", "string"), ("offset", "int", "int"), ("data", "string", "string"), ("eof", "bool", "bool"), ("error", "string", "string"), )

    def __init__(self, file_hash="", offset=0, data="", eof=False, error=""):
        self.file_hash = file_hash
        self.offset = offset
        self.data = data
        self.eof = eof
        self.error = error
        self.message_id = next(_sequence)


class FileWriteRequest(Message):
    NAME = "FileWriteRequest"
    FIELDS = Message.FIELDS + (("directory_hash", "string", "string"), ("name", "string", "string"), ("offset", "int", "int"), ("data", "string", "string"), ("last", "bool", "bool"), )

    def __init__(self, directory_hash="", name="", offset=0, data="", last=False):
        self.directory_hash = directory_hash
        self.name = name
        self.offset = offset
        self.data = data
        self.last = last
        self.message_id = next(_sequence)


class FileWriteReply(Message):
    NAME = "FileWriteReply"
    FIELDS = Message.FIELDS + (("name", "string", "string"), ("offset", "int", "int"), ("ok", "bool", "bool"), ("error", "string", "string"), )

    def __init__(self, name="", offset=0, ok=False, error=""):
        self.name = name
        self.offset = offset
        self.ok = ok
        self.error = error
        self.message_id = next(_sequence)


class MakeDirectoryRequest(Message):
    NAME = "MakeDirectoryRequest"
    FIELDS = Message.FIELDS + (("parent_hash", "string", "string"), ("name", "string", "string"), )

    def __init__(self, parent_hash="", name=""):
        self.parent_hash = parent_hash
        self.name = name
        self.message_id = next(_sequence)


class MakeDirectoryReply(Message):
    NAME = "MakeDirectoryReply"
    FIELDS = Message.FIELDS + (("name", "string", "string"), ("hash", "string", "string"), ("ok", "bool", "bool"), ("error", "string", "string"), )

    def __init__(self, name="", hash="", ok=False, error=""):
        self.name = name
        self.hash = hash
        self.ok = ok
        self.error = error
        self.message_id = next(_sequence)


_CLASSES = {
    "Message": Message,
    "DirectoryEntry": DirectoryEntry,
    "ConnectRequest": ConnectRequest,
    "ConnectionRequestReply": ConnectionRequestReply,
    "Authenticate": Authenticate,
    "AuthenticationStatus": AuthenticationStatus,
    "StatusRequest": StatusRequest,
    "Status": Status,
    "DirectoryListRequest": DirectoryListRequest,
    "DirectoryList": DirectoryList,
    "FileReadRequest": FileReadRequest,
    "FileData": FileData,
    "FileWriteRequest": FileWriteRequest,
    "FileWriteReply": FileWriteReply,
    "MakeDirectoryRequest": MakeDirectoryRequest,
    "MakeDirectoryReply": MakeDirectoryReply,
}


def envelope(msg):
    """Returns the bytes to send for the message, including the terminating NUL."""
    return (_ENVELOPE_HEAD + msg.NAME + '">' + msg.serialize() + "</cld></protocol>").encode("utf-8") + b"\0"


def parse(frame):
    """Parses one frame (without the NUL), returns the message object or None."""
    root = ET.fromstring(frame)
    cld = root if root.tag == "cld" else root.find("cld")
    if cld is None:
        return None
    cls = _CLASSES.get(cld.get("msg", ""))
    if cls is None:
        return None
    return cls.from_node(cld.find("o"))
