#weirdly enough, this is the correct one, watm make still thinks he is in the project root!
utils_dir = ./src/utils
gui_dir = ./src/gui
states_dir = ./src/states

!include $(utils_dir)/makefile
!include $(gui_dir)/makefile
!include $(states_dir)/makefile
